name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v0.1.0'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache Electron
        uses: actions/cache@v4
        with:
          path: ~/.cache/electron
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Electron app (macOS)
        run: pnpm run dist:mac
        env:
          ELECTRON_BUILD: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELECTRON_CACHE: ~/.cache/electron

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: |
            release/*.dmg
            release/*.zip
            release/*.dmg.blockmap
          retention-days: 7

  build-windows:
    runs-on: windows-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache Electron
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\electron\Cache
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Electron app (Windows)
        run: pnpm run dist:win
        env:
          ELECTRON_BUILD: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: |
            release/*.exe
            release/*.zip
            release/*.exe.blockmap
          retention-days: 7

  release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 10
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-app
          path: ./artifacts/macos/

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-app
          path: ./artifacts/windows/

      - name: List artifacts for debugging
        run: |
          echo "=== macOS artifacts ==="
          ls -la ./artifacts/macos/
          echo "=== Windows artifacts ==="
          ls -la ./artifacts/windows/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/macos/*
            ./artifacts/windows/*
          generate_release_notes: true
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
